### ISSUE TITLE
Need way to quickly print out and summarize PO names to make writing estimands easier 

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DeclareDesign-dev#241]
i.e. declare_POs() could say "this will create the following potential outcomes ....". and maybe provide some simple examples of estimands i.e. mean(Y_Z_1 - Y_Z_0,na.rm = TRUE)

**Comment by graemeblair** [comment]
This issue was moved to DeclareDesign/DeclareDesign#48
