### ISSUE TITLE
summarizing each type of object

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign-dev#5]
Hi guys,

In the future (maybe not in version 0.1?), we need a summarize function or functions that can be used to describe or visualize in plot or table the key parts of the registration--covariates, potential outcomes, design, and power. I'm now convinced by Alex that we should basically leave the analysis summarizing to the user. 

- summary(population)
- summary(potential_outcomes)
- summary(sampling)
- summary(assignment) returns a detailed written description of the assignment, i.e. "This is a clustered, block-randomized design with..."
- summary(estimator) -- includes description of estimand it is hitting, if any
Propose a first set that we could do in coming weeks:
- summary(assignment) returns a detailed written description of the assignment, i.e. "This is a clustered, block-randomized design with..."

- power.plot() makes power plots as a function of N or in the future other parameters
- table_experiment_data() returns a table that looks like a summary of realized data for covariates and potential_outcomes, but is instead based on the data definitions
- outcomes_table() which I thought might print a visual or text description of the names and distributions of the potential outcomes; 
- a similar covariates_table() function. 
- histogram_ate() plots a histogram of the distribution of true ATEs in the population as defined by your sampling strategy (Alex's suggestion).
   - Note: one gnarly problem will be multi-arm trials -- need a way to visualize all the relevant comparisons. Another gnarly problem will be summarizing population CATEs - i.e., the expected distribution of the (sample) ATEs among a subgroup.

**Comment by acoppock** [comment]
Love these.  I'll work on summary(design) and histogram_ate().  One gnarly problem will be multi-arm trials -- need a way to visualize all the relevant comparisons.  Another gnarly problem will be summarizing population CATEs - i.e., the expected distribution of the (sample) ATEs among a subgroup.

**Comment by graemeblair** [comment]
Great. I will do power.plot(). Jasper, perhaps you can do table_experiment_data() and summary(potential_outcomes), because writing them will probably involve fooling with the outputs of your functions simultaneously?

**Comment by jaspercooper** [comment]
Yes!

**Comment by macartan** [comment]
Sounds great;
How about optional warnings:
-- You have a blocked design but are not taking account of blocks in your
analysis
-- Your randomization scheme implies unequal propensities but you are not
taking account of this in your analysis
-- Your randomization scheme implies correlated assignments, but...
-- You indicate X as your primary analysis but your power is only good for Y
-- With so many outcomes you might consider adjustments for multiple
comparisons

**Comment by graemeblair** [comment]
Sounds great, you mean at the pre_register() stage when it is going to save the pre-registration doc?
